const router = require('express').Router();
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const { createUser, login } = require('../controllers/users');
const { doesNotExist } = require('../middlewares/does-not-exist');
const { errorHandler } = require('../middlewares/errorHandler');
const usersRouter = require('./users');
const { auth } = require('../middlewares/auth');
const { requestLogger, errorLogger } = require('../middlewares/logger');

router.use(cookieParser());
router.use(bodyParser.json());
router.use(bodyParser.urlencoded({ extended: true }));
router.use(requestLogger);
router.post('/signup', createUser);
router.post('/signin', login);
router.use(auth);
router.use('/users', usersRouter);
router.all('*', doesNotExist);
router.use(errorLogger);
router.use('/', errorHandler);
module.exports = router;
